src/mr.roboto/src/mr/roboto/subscriber.py, src/mr.roboto/src/mr/roboto/views/runcorejob.py
This hint can be added automatically in the pre and postrelease commits done by zest.releaser by adding this in your `~/.pypirc`:
```
[zest.releaser]
extra-message =
[ci skip]
```
This makes sure no mails are sent complaining that a package is not in the checkouts list, which happens because you usually have just taken it out of the checkouts list because you have made a new release. This fixes https://github.com/plone/jenkins.plone.org/issues/128
More importantly, it does not needlessly flood Jenkins when releasing a package.  Currently, when you release a package that is used with the same branch on Plone 4.3. and Plone 5, you get ten Jenkins jobs. You get these five because you have updated the version pin, which is good:
- Plone 4.3 Python 2.6
- Plone 4.3 Python 2.7
- Plone 5
- Plone …
=> Skip Jenkins when [ci skip] is in commit.

src/mr.roboto/src/mr/roboto/subscriber.py, src/mr.roboto/src/mr/roboto/tests/test_warn_pull_request_jobs.py
When a pull request is created or updated,
create pending status messages for all plone versions that should
be checked before the pull request can be safely merged.
=> Create status for all targeted plone versions

src/mr.roboto/src/mr/roboto/events.py, src/mr.roboto/src/mr/roboto/subscriber.py, src/mr.roboto/src/mr/roboto/templates/error_commit_checkout.pt, src/mr.roboto/src/mr/roboto/tests/test_add_to_checkouts.py, src/mr.roboto/src/mr/roboto/tests/test_pull_requests.py, src/mr.roboto/src/mr/roboto/tests/test_subscriber.py, src/mr.roboto/src/mr/roboto/views/pull_requests.py
@tisto @mauritsvanrees is it ok to add the package that got a pull request merged on checkouts.cfg for **all** buildout.coredev branches which track the branch where the pull request was merged to?
Then we should clean them up whenever a release is done, right?
Fixes: https://github.com/plone/mr.roboto/issues/26
=> Auto checkout

src/mr.roboto/src/mr/roboto/tests/test_utils.py, src/mr.roboto/src/mr/roboto/utils.py
This way, when used later on it does not break if the commit message has some non-ascii characters.
=> Encode commit message

src/mr.roboto/src/mr/roboto/templates/github_commit.pt
On fake commits' commit message.
This way the first line (title) of the commit is just "[fc] Repository: REPO NAME"
and all the other details are in the body of the commit message.
Without that extra blank line everything was part of the title.
=> Add an extra blank line

src/mr.roboto/src/mr/roboto/subscriber.py
Fixes issue #48.
Hard for me to try out. But I tested the basics in a Python prompt by using a `unidiff.PatchSet` of `last_commit.txt` from coredev 5.1, and it seems that this PR would indeed detect changes in the news directory.
=> Accept changes in the news/ directory as valid changelog entry.

src/mr.roboto/src/mr/roboto/buildout.py
The `SouresFile` and `CheckoutsFile` were reading (i.e. opening and closing the file) on **every single** read operation on the file.
So, updating sources and checkouts read the file an incredible amount of times :sweat_smile:
=> Read files once

src/mr.roboto/src/mr/roboto/subscriber.py
Only warn about triggering jenkins jobs when is a core package
targeting a branch in a plone branch.
=> Update when to trigger jobs

src/mr.roboto/src/mr/roboto/__init__.py, src/mr.roboto/src/mr/roboto/buildout.py, src/mr.roboto/src/mr/roboto/subscriber.py, src/mr.roboto/src/mr/roboto/tests/__init__.py, src/mr.roboto/src/mr/roboto/tests/test_buildout.py, src/mr.roboto/src/mr/roboto/tests/test_changelog_entry.py, src/mr.roboto/src/mr/roboto/tests/test_comments.py, src/mr.roboto/src/mr/roboto/tests/test_config.py, src/mr.roboto/src/mr/roboto/tests/test_pull_requests.py, src/mr.roboto/src/mr/roboto/tests/test_runcorejob.py, src/mr.roboto/src/mr/roboto/tests/test_runhooks.py, src/mr.roboto/src/mr/roboto/tests/test_simple_views.py, src/mr.roboto/src/mr/roboto/tests/test_warn_pull_request_jobs.py, src/mr.roboto/src/mr/roboto/views/runcorejob.py
With the test suite it does work. I simplified the code so that there is no difference between plone versions and plone on python 3 versions. As `python_versions` is a dictionary, one can just add `2.7` on `5.2` and that's it.
⚠️ Minor/major change though: the jobs on jenkins will need to be renamed only once this pull request gets deployed!
=> Py versions per plone version

src/mr.roboto/src/mr/roboto/buildout.py
This is a workaround for issue https://github.com/plone/mr.roboto/issues/82
Should prevent this error with coredev 6.0 sources.cfg:
```
backports.configparser.InterpolationMissingOptionError:
Bad value substitution: option 'docs-classicui' in section 'sources' contains an interpolation key 'buildout:directory' which is not a valid option name.
Raw value: 'git ${remotes:plone}/documentation.git pushurl=${remotes:plone_push}/documentation.git egg=false branch=classic-ui path=${buildout:directory}/documentation/classic-ui'
```
=> Insert buildout:directory in config.

src/mr.roboto/src/mr/roboto/buildout.py
`Source` class already has a `path` property, if trying to set one via `setattr` python raises an exception.
This happens on `buildout.coredev` branch 6.0 where there are some documentation related sources that have an extra `path` attribute on their definition.
This should fix #82
=> Do not set path attribute

.gitignore, Makefile, setup.cfg, src/mr.roboto/CONTRIBUTORS.rst, src/mr.roboto/src/mr/roboto/subscriber.py
Clarify that usually contributors should get all other checks passing before running the
Plone Jenkins PR jobs and add a link to the Plone Jenkins docs.  Also fix some typos and
do some other editing for brevity and clarity.
Fixes #84
Also includes capturing some cleanup and local development build and set up I did along
the way.
=> docs(prs): Clarify automatic PR comment text

src/mr.roboto/src/mr/roboto/buildout.py
Workaround for https://github.com/plone/mr.roboto/issues/89
=> Insert buildout:docs-directory when reading sources.

src/mr.roboto/src/mr/roboto/subscriber.py
Not all packages should be automatically added on `checkouts.cfg`
Should fix https://github.com/plone/buildout.coredev/issues/768
=> Add exception list of auto checkout packages

src/mr.roboto/src/mr/roboto/subscriber.py
It uses release-it to create a changelog out of the commit messages.
See small discussion in Discord in the classic-ui channel.
=> No changelog verifier needed for mockup.

src/mr.roboto/src/mr/roboto/templates/home.pt, src/mr.roboto/src/mr/roboto/views/runhooks.py
Much more useful than to running on all plone and some collective repos when a new repository is added on Plone organization.
Closes #73
=> feat: allow re-creating hooks for one single repo

src/mr.roboto/src/mr/roboto/subscriber.py
This PR updates the links to the Plone Contributor Agreement away from Plone 5 documentation and to a (hopefully) permalink on plone.org. It also updates a link to GitHub docs to save a redirect.
Refs: https://github.com/plone/volto/pull/4591#issuecomment-1481461700
@gforcada @sneridagh @fredvd @mauritsvanrees
=> Update links to Contributor Agreement, GitHub docs

src/mr.roboto/src/mr/roboto/subscriber.py
As seen on https://github.com/plone/plone.app.mosaic/pull/532 for example.
We need to ignore that user as well to request the contributor agreement.
=> dependabot has a new name

src/mr.roboto/src/mr/roboto/subscriber.py
On PRs that modify the pre-commit configuration file.
They will be either be done via `plone/meta` configuration that already creates a news entry, or via `pre-commit.ci` service itself.
This way the missing valid changelog entry will not be required 👍🏾 
Closes #111
=> feat: do not require changelog

src/mr.roboto/src/mr/roboto/subscriber.py
It is not released per se, and we can see what changed in the git history.
=> Add `.github` repo to IGNORE_NO_CHANGELOG

src/mr.roboto/src/mr/roboto/subscriber.py
As it's an auxiliary tool rather than code that runs within Plone.
=> feat: skip jenkins jobs for plone.versioncheck

src/mr.roboto/src/mr/roboto/subscriber.py, src/mr.roboto/src/mr/roboto/views/runhooks.py
See https://github.com/collective/icalendar/pull/514#issuecomment-1506108571 and following comments. From a Plone core development perspective, `icalendar` is a third party package since a while. It is used a lot outside of Plone, and is taken care of by people who are not core Plone developers.
The `plone.app.event` tests are run on every PR of this package, see [yaml file](https://github.com/collective/icalendar/blob/v5.0.5/.github/workflows/tests.yml#L26) and [`tox.ini`](https://github.com/collective/icalendar/blob/v5.0.5/tox.ini#L27). I keep tabs on new versions, and manually update its version in `buildout.coredev`. So nothing is needed on Jenkins, so `mr.roboto` does not need to do anything.  I have removed the roboto hooks in the settings of the `icalendar` repo.
But: checking for …
=> icalendar: only run the changelog test.

requirements-app.in, requirements-app.txt, requirements-dev.txt
Now to run `mr.roboto` locally one only has to:
```shell
python3.11 -m venv .
. bin/activate
pip install pip-tools
pip-sync requirements-app.txt
pip install -e src/mr.roboto
cp development.ini.sample development.ini
./bin/pserve development.ini
```
We are one step closer to remove `buildout` from the equation and deploy and update dependencies much more easily and reliable 🍀
=> Add missing packages to run mr.roboto

src/mr.roboto/src/mr/roboto/subscriber.py, src/mr.roboto/src/mr/roboto/tests/test_add_to_checkouts.py
99% of the time that pre-commit.ci is creating a PR it only modifies its configuration, as it bumps the hooks' versions.
It is a waste of resources to create a commit for that on buildout.coredev, nor it makes any sense to make a new release of a package due to pre-commit hooks being updated.
Closes #120
=> feat: no coredev commits for pre-commit CI PRs

CHANGES.md, src/mr.roboto/src/mr/roboto/tests/test_simple_views.py, src/mr.roboto/src/mr/roboto/views/home.py, tox.ini
Since the buildout removal and the upgrade to python 3.11 the log format
is slightly different.
=> Fix log parsing

CHANGES.md, src/mr.roboto/src/mr/roboto/subscriber.py, src/mr.roboto/src/mr/roboto/tests/test_add_to_checkouts.py, src/mr.roboto/src/mr/roboto/tests/test_utils.py, src/mr.roboto/src/mr/roboto/utils.py, src/mr.roboto/src/mr/roboto/views/runcorejob.py
If a PR is merged and the commit message has a `[ci-skip]` text mark on it, then do not create a commit on buildout.coredev nor add the package where the PR got merged into `checkouts.cfg`.
=> feat: skip coredev commits on request

src/mr.roboto/src/mr/roboto/subscriber.py, src/mr.roboto/src/mr/roboto/tests/test_warn_pull_request_jobs.py
We already have it in the `IGNORE_NO_TEST_NEEDED`, but the [comment asking to trigger Jenkins jobs is still added](https://github.com/plone/plone.releaser/pull/76#issuecomment-2343020247).
Actually, if a package is in `IGNORE_NO_TEST_NEEDED`, then even if you would trigger Jenkins jobs, nothing would happen, if I follow the code correctly.  Indeed, I added that comment for triggering the jobs, but the robots log says:
> INFO COMMENT [plone/plone.releaser#76-2343059679](https://github.com/plone/plone.releaser/pull/76#issuecomment-2343059679): skip triggering jenkins jobs, repo is ignored
So let me add another commit to this PR to add the `IGNORE_NO_TEST_NEEDED` packages to `IGNORE_NO_JENKINS`.
=> Do not add Jenkins comment for plone.releaser PRs.

src/mr.roboto/src/mr/roboto/subscriber.py
Closes #163.
See also:
- https://github.com/plone/documentation/pull/1722
- https://github.com/plone/documentation/issues/1716
=> Rewrite unknown emails to account for emails on commits

.pre-commit-config.yaml, src/mr.roboto/src/mr/roboto/subscriber.py, src/mr.roboto/src/mr/roboto/tests/test_add_to_checkouts.py, src/mr.roboto/src/mr/roboto/tests/test_buildout.py
See https://github.com/plone/mr.roboto/pull/new/weblate
I also needed to update the pre-commit versions to avoid a really wrong complaint by flake8, see first commit.
=> Don't check user agreement for weblate user
